name: modular_navigation
description: Modular Navigation
version: 0.0.29
homepage: https://github.com/4D-Technologies/modular_navigation

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
