name: modular_navigation
description: Modular Navigation
version: 0.0.2
homepage: https://github.com/Concerti-IO/modular_navigation
publish_to: https://pub.dev/modular_navigation

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.2
  flutter_test:
    sdk: flutter

flutter:
