name: modular_navigation
description: Modular Navigation
version: 0.0.28
homepage: https://github.com/Concerti-IO/modular_navigation

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
